name: Deploy PowerMonitor Site

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # needed to push tags later

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install --force

    - name: Setup Git identity
      run: |
        git config --global user.email "xhunter74@gmail.com"
        git config --global user.name "Serhiy Krasovskyy"

    - name: Build project
      run: npm run build-prod

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v13.0.1
      with:
        args: deploy --project ${{ secrets.PROJECT_ID }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Commit and tag version
      run: |
        appversion=$(node app-version.js)

        git add package.json
        git add package-lock.json
        git add src/environments/environment.prod.ts

        git commit -m "[skip ci] Updated Powermonitor site version to $appversion." || echo "No changes to commit"

        git tag -a v$appversion -m "Site version $appversion"
        
        git push origin master --tags
