name: Deploy PowerMonitor Site

on:
    push:
        branches:
            - master

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            src_changed: ${{ steps.src-changes.outputs.src_changed }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Lint code
              run: npm run lint

            - name: Run tests
              run: npm run test

            - name: Build project
              run: npm run build-prod

            - name: Upload build artifact (dist)
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/

            - name: Upload build artifact (versioned files)
              uses: actions/upload-artifact@v4
              with:
                  name: versioned-files
                  path: |
                      package.json
                      package-lock.json
                      src/environments/environment.prod.ts

            - name: Check for changes in src folder
              id: src-changes
              run: |
                  if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^src/'; then
                    echo "src_changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "src_changed=false" >> $GITHUB_OUTPUT
                  fi

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: needs.build.outputs.src_changed == 'true'
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Download build artifact (dist)
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist

            - name: Download build artifact (versioned files)
              uses: actions/download-artifact@v4
              with:
                  name: versioned-files
                  path: ./

            - name: Setup Git identity
              run: |
                  git config --global user.email "xhunter74@gmail.com"
                  git config --global user.name "Serhiy Krasovskyy"

            - name: Write service account key to file
              run: |
                  echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > "${{ github.workspace }}/firebase-key.json"
              shell: bash

            - name: Deploy to Firebase with service account
              run: |
                  npm install -g firebase-tools
                  firebase deploy --project ${{ secrets.PROJECT_ID }} --non-interactive
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json

            - name: Commit and tag version
              run: |
                  appversion=$(node app-version.js)

                  git add package.json
                  git add package-lock.json
                  git add src/environments/environment.prod.ts

                  git commit -m "[skip ci] Updated Powermonitor site version to $appversion." || echo "No changes to commit"
                  git tag -a v$appversion -m "Site version $appversion"
                  git push origin master --tags
