name: Deploy PowerMonitor Site

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # needed to push tags later

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Setup Git identity
      run: |
        git config --global user.email "xhunter74@gmail.com"
        git config --global user.name "Serhiy Krasovskyy"

    - name: Build project
      run: npm run build-prod

    - name: Run tests
      run: npm run test

    - name: Check for changes in src folder
      id: src-changes
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^src/'; then
          echo "src_changed=true" >> $GITHUB_ENV
        else
          echo "src_changed=false" >> $GITHUB_ENV
        fi

    - name: Write service account key to file
      if: env.src_changed == 'true'
      run: |
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > "${{ github.workspace }}/firebase-key.json"
      shell: bash
    
    - name: Deploy to Firebase with service account
      if: env.src_changed == 'true'
      run: |
        npm install -g firebase-tools
        firebase deploy --project ${{ secrets.PROJECT_ID }} --non-interactive
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json

    - name: Commit and tag version
      if: env.src_changed == 'true'
      run: |
        appversion=$(node app-version.js)

        git add package.json
        git add package-lock.json
        git add src/environments/environment.prod.ts

        git commit -m "[skip ci] Updated Powermonitor site version to $appversion." || echo "No changes to commit"
        git tag -a v$appversion -m "Site version $appversion"
        git push origin master --tags
